from enum import Enum, auto


class PortfolioConstants(Enum):
    ACCEPTED_DUPLICATION_PERCENTAGE = 0
    ACCEPTED_DUPLICATION_PERCENTAGE_CRAWL = 5
    ACCEPTED_NULL_RECORDS_PERCENTAGE = 0
    ACCEPTED_NULL_RECORDS_PERCENTAGE_CRAWL = 5
    TRANSACTION_TABLE_SIZE_LIMIT = 30.0
    THRESHOLD_RECORD_COUNT_FOR_ANALYSIS = 5
